name: deploy
on:
    push:
      branches:
        - main
jobs:
  publish:
    name: build
    permissions:
        contents: write
        id-token: write   # to verify the deployment originates from an appropriate source
        deployments: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
      - run: flutter --version
      - name: Install dependencies
        run: dart pub get
      - name: Build
        run: flutter build web --base-href "/split_frontend/" --dart-define=ENVIRONMENT=dev --web-renderer html

      - name: Commit report
        run: |
          git checkout -b docs
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git commit -am "Automated report"
          git push
